#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
echo $BASHPID > /run/"$(basename $0)".pid

function clean_1() {
	rm -f /run/$(basename $0).pid
}

trap "clean_1; exit" 0 1 2 3 15

function agregar() {
	if [[ $? = 0 ]]; then
		echo -e "\e[00;1;92mArchivos agregados correctamente.\e[00m"
	else
		echo -e "\e[00;31mError al agregar archivos.\e[00m"
		exit 1
	fi
}

function hacercommit() {
	if [[ $? = 0 ]]; then
		echo -e "\e[00;1;92mCommit realizado correctamente.\e[00m"
	else
		echo -e "\e[00;31mError al realizar commit.\e[00m"
		exit 1
	fi
}

function hacerpush() {
	if [[ $? = 0 ]]; then
		echo -e "\e[00;1;92mEnvio realizado correctamente.\e[00m"
	else
		echo -e "\e[00;31mError al realizar envio.\e[00m"
		exit 1
	fi
}

case "$1" in
	up)
		if [ -n "$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)" ]; then
			echo 1 > /dev/null
		else
			echo "push_location = bzr+ssh://bazaar.launchpad.net/"$(cat .bzr/branch/branch.conf | grep parent_location | cut -c 50-99) >> .bzr/branch/branch.conf
		fi
		bzrvar="lp:$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)"
		bzr add
		agregar
		bzr commit
		hacercommit
		bzr push "$bzrvar"
		hacerpush
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;	

	up-all)
		for i in $(find . -maxdepth 1 -type d | cut -c 3-50); do
			cd $i
				if [ -n "$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)" ]; then
					echo 1 > /dev/null
				else
					echo "push_location = bzr+ssh://bazaar.launchpad.net/"$(cat .bzr/branch/branch.conf | grep parent_location | cut -c 50-99) >> .bzr/branch/branch.conf
				fi
				bzrvar2="lp:$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)"
				echo -e "\e[00;1;92m$(pwd)\e[00m"
				bzr add
				agregar
				bzr commit -m $2
				hacercommit
				bzr push "$bzrvar2"
				hacerpush
			cd ..
		done
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	init)
		echo "Introduzca su nombre de usuario en Bazaar:"
		read yo
		echo "Introduzca el nombre de la rama:"
		read donde
		bzr init
		bzr add
		agregar
		bzr commit -m "* first commit"
		hacercommit
		bzr push lp:~"$yo"/+junk/"$donde"
		hacerpush
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	change)
		if [ -n "$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)" ]; then
			echo 1 > /dev/null
		else
			echo "push_location = bzr+ssh://bazaar.launchpad.net/"$(cat .bzr/branch/branch.conf | grep parent_location | cut -c 50-99) >> .bzr/branch/branch.conf
		fi
		bzrvar="lp:$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)"		
		bzr log > CHANGES
		bzr add
		agregar
		bzr commit -m "* changelog"
		hacercommit
		bzr push "$bzrvar"
		hacerpush
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	change-all)
		for i in $(find . -maxdepth 1 -type d | cut -c 3-50); do
			cd $i
				if [ -n "$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)" ]; then
					echo 1 > /dev/null
				else
					echo "push_location = bzr+ssh://bazaar.launchpad.net/"$(cat .bzr/branch/branch.conf | grep parent_location | cut -c 50-99) >> .bzr/branch/branch.conf
				fi
				bzrvar2="lp:$(cat .bzr/branch/branch.conf | grep push_location | cut -c 48-99)"
				echo -e "\e[00;1;92m$(pwd)\e[00m"
				bzr log > CHANGES
				bzr add
				agregar
				bzr commit -m "* changelog"
				hacercommit
				bzr push "$bzrvar2"
				hacerpush
			cd ..
		done
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	refresh)
		for i in $(find . -maxdepth 1 -type d | cut -c 3-50); do
    			cd $i
			echo -e "\e[00;1;92m$(pwd)\e[00m"
			bzr pull
			cd ..
		done
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	break)
		bzr break-lock --force
		bzr break-lock --force bzr+ssh://bazaar.launchpad.net/$(cat .bzr/branch/branch.conf | grep parent_location | cut -c 50-99)
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	install)
		if [[ "$EUID" != "0" ]]; then
			echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
			exit 1
		fi
		apt-get -q update
		apt-get -qy install bzr
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	*)
		echo "uso: $(basename $0) {install|up|init|break|change|change-all|refresh|up-all <msj>}"
		;;
esac
exit 0
